//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horn.PackageDoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Expressions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Expressions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Horn.PackageDoc.Properties.Expressions", typeof(Expressions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package.category\s*?=\s*?&quot;(?&lt;category&gt;.*?)&quot;.
        /// </summary>
        internal static string PackageCategory {
            get {
                return ResourceManager.GetString("PackageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?sxm)\s.*package.description\s*?=\s*?&quot;(?&lt;description&gt;.*?)&quot;.
        /// </summary>
        internal static string PackageDescription {
            get {
                return ResourceManager.GetString("PackageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?sxm)\s.*package.forum\s*?=\s*?&quot;(?&lt;forumurl&gt;.*?)&quot;.
        /// </summary>
        internal static string PackageForumUrl {
            get {
                return ResourceManager.GetString("PackageForumUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?sxm)\s.*package.homepage\s*?=\s*?&quot;(?&lt;homepageurl&gt;.*?)&quot;.
        /// </summary>
        internal static string PackageHomepageUrl {
            get {
                return ResourceManager.GetString("PackageHomepageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?sxm)install\s(?&lt;id&gt;.*?):.
        /// </summary>
        internal static string PackageId {
            get {
                return ResourceManager.GetString("PackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?sxm)\s.*package.name\s*?=\s*?&quot;(?&lt;name&gt;.*?)&quot;.
        /// </summary>
        internal static string PackageName {
            get {
                return ResourceManager.GetString("PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?sxm)\s.*package.notes\s*?=\s*?&quot;(?&lt;notes&gt;.*?)&quot;.
        /// </summary>
        internal static string PackageNotes {
            get {
                return ResourceManager.GetString("PackageNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?sxm)\s.*package.version\s*?=\s*?&quot;(?&lt;version&gt;.*?)&quot;.
        /// </summary>
        internal static string PackageVersion {
            get {
                return ResourceManager.GetString("PackageVersion", resourceCulture);
            }
        }
    }
}
